# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=50)),
                ('comment_pub_date', models.DateTimeField(verbose_name='date comment published')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=300)),
                ('post_pub_date', models.DateTimeField(verbose_name='date published')),
                ('headers', models.CharField(max_length=20)),
            ],
        ),
    ]
