# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20170708_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headers',
            new_name='header',
        ),
    ]
