# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default='', upload_to='static/downloads/'),
        ),
    ]
