# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20170709_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(default='static/blogapp/downloads/default.jpg', upload_to='static/downloads/'),
        ),
    ]
