# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20170709_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=1000),
        ),
    ]
