# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
