# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20170809_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myemail',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='myemail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
