# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_remove_myemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myemail',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
